config/routes.rb
Trellino::Application.routes.draw do
  root to: 'static_pages#root'

  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit] do
      resources :lists, only: [:index, :show, :create, :update, :destroy]
    end
    resources :lists, only: [:show, :update, :destroy] do
      resources :cards, only: [:create, :index]
    end
    resources :cards, only: [:show, :update, :destroy] do
      resources :todo_items, only: [:create, :index]
      resources :comments
    end
    resources :todo_items, only: [:show, :update, :destroy]
    resources :card_assignments, only: :destroy
  end

  # resources :static_pages, only: [:new]

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]

end

app/views/layouts/_errors.html.erb
<% flash[:errors] && flash[:errors].each do |error| %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" 
      class="close" 
      data-dismiss="alert" 
      aria-hidden="true">&times;</button>
    <strong>Error:</strong>
    <%= error %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Listatask</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico'%>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
				<a href="#">
					<div class="logo" ><%= image_tag("listatasklogo.png")%></div>
				</a>
				<a class="navbar-brand" href="#">Listatask</a>
      </div>

      <ul class="nav navbar-right nav-pills">
        <li>
          <% if logged_in? %>
					<li>
				      <button class="btn trello-button-format" data-toggle="modal" data-target="#add-member">
				        Add member
				      </button>

				</li>
					<li>
            <%= button_to "Log out", session_url, { method: :delete, class: "btn trello-button-format" } %>
					</li>

					<% else  %>
						<% link_to new_session_url %>


          <% end %>
        </li>

      </ul>
    </div>
  </nav>


  <%= yield %>
				    <div class="modal fade" id="add-member" tableindex="-1" role="dialog" aria-labelleby="myModalLabel" aria-hidden="true">
				      <div class="modal-dialog">
				        <div class="modal-content">
				          <div class="modal-header">
				          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				          <h4 class="modal-title" id="myModalLabel">Add Member</h4>
				            <div class="modal-body">
				              <form class="add-member trello-button-format">
				                <label>Enter the member's Email
				                  <input type="text" name="newMemberEmail">
				                </label>
				                  <br>
				                  <input class='btn' type='Submit' >
				                </form>
				              </div>
				            </div>
				          <div>
				        </div>
				      </div>
				    </div>
				  </div>
</body>
</html>